package org.example.controllers;

import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.Stage;
import org.example.entities.Matching;
import org.example.services.ServiceMatching;

import java.sql.SQLException;
import java.time.LocalDate;

public class AddMatchingController {

    @FXML private TextField cinField;
    @FXML private TextArea descriptionField;
    @FXML private DatePicker dateField;
    @FXML private TextField competencesField;
    @FXML private TextField priceField;

    private Runnable refreshCallback;  // Changed from Consumer<Void> to Runnable
    private ServiceMatching serviceMatching = new ServiceMatching();

    public void setRefreshCallback(Runnable callback) {  // Changed parameter type
        this.refreshCallback = callback;
    }

    @FXML
    private void handleSave() {
        try {
            // Validate CIN
            String cin = cinField.getText().trim();
            if (cin.isEmpty() || !cin.matches("\\d{8}")) {
                showAlert("Validation Error", "Please enter a valid 8-digit CIN.");
                return;
            }

            // Validate Description
            String description = descriptionField.getText().trim();
            if (description.isEmpty()) {
                showAlert("Validation Error", "Description cannot be empty.");
                return;
            }

            // Validate Date
            LocalDate date = dateField.getValue();
            if (date == null) {
                showAlert("Validation Error", "Please select a valid date.");
                return;
            } else if (date.isBefore(LocalDate.now())) {
                showAlert("Validation Error", "The date cannot be in the past.");
                return;
            }

            // Validate Competences
            String competences = competencesField.getText().trim();
            if (competences.isEmpty()) {
                showAlert("Validation Error", "Competences field cannot be empty.");
                return;
            }

            // Validate Price
            String priceText = priceField.getText().trim();
            float price;
            if (priceText.isEmpty()) {
                showAlert("Validation Error", "Price cannot be empty.");
                return;
            }
            try {
                price = Float.parseFloat(priceText);
                if (price < 0) {
                    showAlert("Validation Error", "Price must be a positive number.");
                    return;
                }
            } catch (NumberFormatException e) {
                showAlert("Validation Error", "Price must be a valid number.");
                return;
            }

            // If all fields are valid, create and save the matching
            Matching matching = new Matching(
                    0, // ID will be generated by the database
                    cin,
                    description,
                    date,
                    competences,
                    null, // cv path
                    price,
                    false // availability
            );

            serviceMatching.add(matching);

            if (refreshCallback != null) {
                refreshCallback.run();
            }

            closeWindow();

        } catch (SQLException e) {
            showAlert("Database Error", "Failed to save matching: " + e.getMessage());
        }
    }


    @FXML
    private void handleCancel() {
        closeWindow();
    }

    private void closeWindow() {
        Stage stage = (Stage) cinField.getScene().getWindow();
        stage.close();
    }

    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle(title);
        alert.setContentText(message);
        alert.showAndWait();
    }
}