knp_paginator:
    page_range: 5 # Nombre de pages visibles avant et après la page actuelle
    default_options:
        page_name: page 
        sort_field_name:
        sort_direction_name: direction 
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Pour Bootstrap 5
